### ISSUE TITLE
Move to readthedocs organization

### ISSUE THREAD

**Issue by agjohnson** [ericholscher/time-test#7]
This repo should probably exist on readthedocs organization and should have shared permissions for the core team.

**Comment by agjohnson** [comment]
Put this on our roadmap, but also can't assign the issues because I don't have permissions on this repo.

cc @ericholscher

**Comment by agjohnson** [comment]
I've forked to my personal user for now. I didn't fork to readthedocs organization, as we'll want to move this repo in the organization instead.

**Comment by agjohnson** [comment]
Ping @ericholscher

**Comment by ericholscher** [comment]
@agjohnson Migrated!

**Comment by agjohnson** [comment]
Thanks! I'll put #9 on our roadmap next, to undo my hack and fix up the build:large testing
